// configs/tanah/peternakan/informasi-tambahan.ts

const informasiTambahan = {
  id: "informasi-tambahan",
  title: "Informasi Tambahan",
  description: "Informasi pendukung mengenai lahan peternakan.",

  fields: [
    {
      id: "property_advantages",
      label: "Keunggulan Properti",
      type: "textarea",
      required: false,
      rows: 5,
      maxLength: 3000,
      placeholder: "Jelaskan keunggulan utama lahan peternakan...",
    },
    {
      id: "selling_reason",
      label: "Alasan Dijual",
      type: "textarea",
      required: false,
      rows: 4,
      maxLength: 2000,
    },
    {
      id: "negotiable",
      label: "Harga Bisa Nego",
      type: "radio",
      required: false,
      options: ["Ya", "Tidak"],
    },
    {
      id: "available_for_survey",
      label: "Bersedia Survey",
      type: "radio",
      required: false,
      options: ["Ya", "Tidak"],
    },
    {
      id: "survey_schedule",
      label: "Jadwal Survey",
      type: "textarea",
      required: false,
      rows: 3,
      maxLength: 1000,
    },
    {
      id: "partial_sale_allowed",
      label: "Bisa Dijual Sebagian",
      type: "radio",
      required: false,
      options: ["Ya", "Tidak"],
    },
    {
      id: "equipment_included",
      label: "Peralatan Peternakan Ikut Dijual",
      type: "radio",
      required: false,
      options: ["Ya", "Sebagian", "Tidak"],
    },
    {
      id: "owner_notes",
      label: "Catatan Pemilik",
      type: "textarea",
      required: false,
      rows: 4,
      maxLength: 2000,
    },
    {
      id: "agent_notes",
      label: "Catatan Agen",
      type: "textarea",
      required: false,
      rows: 4,
      maxLength: 2000,
    },
    {
      id: "internal_reference",
      label: "Referensi Internal",
      type: "text",
      required: false,
      maxLength: 100,
    },
    {
      id: "tags",
      label: "Tag Properti",
      type: "tags",
      required: false,
      placeholder: "Peternakan Ayam, Kandang Permanen, dll",
    },
    {
      id: "seo_keywords",
      label: "Keyword SEO",
      type: "tags",
      required: false,
      placeholder: "Lahan Peternakan Dijual, Kandang Ayam Siap Pakai, dll",
    },
    {
      id: "additional_information",
      label: "Informasi Tambahan",
      type: "textarea",
      required: false,
      rows: 6,
      maxLength: 5000,
      placeholder: "Informasi lain yang belum tercakup...",
    },
  ],
};

export default informasiTambahan;
