// configs/hunian/rumah/informasi-bangunan.ts

const informasiBangunan = {
  id: "informasi-bangunan",
  title: "Informasi Bangunan",
  description: "Informasi identitas dan karakteristik bangunan rumah.",

  fields: [
    {
      id: "housing_name",
      label: "Nama Perumahan",
      type: "text",
      required: false,
      placeholder: "Contoh: Grand Wisata",
    },
    {
      id: "cluster_name",
      label: "Nama Cluster",
      type: "text",
      required: false,
      placeholder: "Contoh: Cluster Emerald",
    },
    {
      id: "developer",
      label: "Developer",
      type: "text",
      required: false,
      placeholder: "Contoh: Sinarmas Land",
    },
    {
      id: "block",
      label: "Blok",
      type: "text",
      required: false,
      placeholder: "Contoh: A",
    },
    {
      id: "house_number",
      label: "Nomor Rumah",
      type: "text",
      required: false,
      placeholder: "Contoh: A-12",
    },
    {
      id: "house_type",
      label: "Tipe Rumah",
      type: "select",
      required: true,
      options: [
        "21",
        "27",
        "36",
        "45",
        "54",
        "60",
        "70",
        "90",
        "120",
        "150",
        "180",
        "200",
        "Custom",
      ],
    },
    {
      id: "architecture_style",
      label: "Gaya Arsitektur",
      type: "select",
      required: false,
      options: [
        "Minimalis",
        "Modern",
        "Japandi",
        "Scandinavian",
        "Industrial",
        "Classic",
        "Mediterania",
        "Tropis",
        "Kontemporer",
        "Lainnya",
      ],
    },
    {
      id: "building_year",
      label: "Tahun Dibangun",
      type: "number",
      required: false,
    },
    {
      id: "renovation_year",
      label: "Tahun Renovasi Terakhir",
      type: "number",
      required: false,
    },
    {
      id: "floors",
      label: "Jumlah Lantai",
      type: "select",
      required: true,
      options: ["1", "2", "3", "4", ">4"],
    },
    {
      id: "house_position",
      label: "Posisi Rumah",
      type: "select",
      required: false,
      options: [
        "Tengah",
        "Hook",
        "Tusuk Sate",
        "Pinggir Jalan",
        "Dalam Cluster",
      ],
    },
    {
      id: "facing",
      label: "Hadap Rumah",
      type: "select",
      required: false,
      options: [
        "Utara",
        "Selatan",
        "Timur",
        "Barat",
        "Timur Laut",
        "Tenggara",
        "Barat Laut",
        "Barat Daya",
      ],
    },
    {
      id: "building_width",
      label: "Lebar Bangunan",
      type: "number",
      required: false,
      suffix: "m",
    },
    {
      id: "building_length",
      label: "Panjang Bangunan",
      type: "number",
      required: false,
      suffix: "m",
    },
    {
      id: "frontage",
      label: "Lebar Muka",
      type: "number",
      required: false,
      suffix: "m",
    },
    {
      id: "ceiling_height",
      label: "Tinggi Plafon",
      type: "number",
      required: false,
      suffix: "m",
    },
    {
      id: "occupancy_status",
      label: "Status Hunian",
      type: "select",
      required: false,
      options: [
        "Kosong",
        "Dihuni Pemilik",
        "Disewakan",
        "Siap Huni",
      ],
    },
    {
      id: "building_condition",
      label: "Kondisi Bangunan",
      type: "select",
      required: true,
      options: [
        "Baru",
        "Bekas",
        "Renovasi Sebagian",
        "Renovasi Total",
        "Dalam Pembangunan",
      ],
    },
    {
      id: "interior_condition",
      label: "Kondisi Interior",
      type: "select",
      required: false,
      options: [
        "Sangat Baik",
        "Baik",
        "Cukup",
        "Perlu Renovasi",
      ],
    },
    {
      id: "exterior_condition",
      label: "Kondisi Eksterior",
      type: "select",
      required: false,
      options: [
        "Sangat Baik",
        "Baik",
        "Cukup",
        "Perlu Renovasi",
      ],
    },
    {
      id: "ever_occupied",
      label: "Pernah Dihuni",
      type: "radio",
      required: false,
      options: ["Ya", "Tidak"],
    },
  ],
};

export default informasiBangunan;
