// configs/hunian/rumah/spesifikasi-bangunan.ts

const spesifikasiBangunan = {
  id: "spesifikasi-bangunan",
  title: "Spesifikasi Bangunan",
  description: "Spesifikasi fisik rumah.",

  fields: [
    {
      id: "land_area",
      label: "Luas Tanah",
      type: "number",
      required: true,
      suffix: "m²",
    },
    {
      id: "building_area",
      label: "Luas Bangunan",
      type: "number",
      required: true,
      suffix: "m²",
    },
    {
      id: "building_width",
      label: "Lebar Bangunan",
      type: "number",
      required: false,
      suffix: "m",
    },
    {
      id: "building_length",
      label: "Panjang Bangunan",
      type: "number",
      required: false,
      suffix: "m",
    },
    {
      id: "front_width",
      label: "Lebar Muka",
      type: "number",
      required: false,
      suffix: "m",
    },
    {
      id: "land_length",
      label: "Panjang Tanah",
      type: "number",
      required: false,
      suffix: "m",
    },
    {
      id: "floors",
      label: "Jumlah Lantai",
      type: "number",
      required: true,
    },
    {
      id: "bedrooms",
      label: "Kamar Tidur",
      type: "number",
      required: true,
    },
    {
      id: "maid_bedrooms",
      label: "Kamar Tidur Pembantu",
      type: "number",
      required: false,
    },
    {
      id: "bathrooms",
      label: "Kamar Mandi",
      type: "number",
      required: true,
    },
    {
      id: "maid_bathrooms",
      label: "Kamar Mandi Pembantu",
      type: "number",
      required: false,
    },
    {
      id: "living_room",
      label: "Ruang Tamu",
      type: "checkbox",
      required: false,
    },
    {
      id: "family_room",
      label: "Ruang Keluarga",
      type: "checkbox",
      required: false,
    },
    {
      id: "dining_room",
      label: "Ruang Makan",
      type: "checkbox",
      required: false,
    },
    {
      id: "workspace",
      label: "Ruang Kerja",
      type: "checkbox",
      required: false,
    },
    {
      id: "prayer_room",
      label: "Ruang Ibadah",
      type: "checkbox",
      required: false,
    },
    {
      id: "clean_kitchen",
      label: "Dapur Bersih",
      type: "checkbox",
      required: false,
    },
    {
      id: "dirty_kitchen",
      label: "Dapur Kotor",
      type: "checkbox",
      required: false,
    },
    {
      id: "pantry",
      label: "Pantry",
      type: "checkbox",
      required: false,
    },
    {
      id: "laundry_room",
      label: "Laundry Room",
      type: "checkbox",
      required: false,
    },
    {
      id: "warehouse",
      label: "Gudang",
      type: "checkbox",
      required: false,
    },
    {
      id: "walk_in_closet",
      label: "Walk In Closet",
      type: "checkbox",
      required: false,
    },
    {
      id: "balcony",
      label: "Balkon",
      type: "checkbox",
      required: false,
    },
    {
      id: "front_terrace",
      label: "Teras Depan",
      type: "checkbox",
      required: false,
    },
    {
      id: "back_terrace",
      label: "Teras Belakang",
      type: "checkbox",
      required: false,
    },
    {
      id: "front_garden",
      label: "Taman Depan",
      type: "checkbox",
      required: false,
    },
    {
      id: "back_garden",
      label: "Taman Belakang",
      type: "checkbox",
      required: false,
    },
    {
      id: "private_pool",
      label: "Kolam Renang Pribadi",
      type: "checkbox",
      required: false,
    },
    {
      id: "gazebo",
      label: "Gazebo",
      type: "checkbox",
      required: false,
    },
    {
      id: "electric_power",
      label: "Daya Listrik",
      type: "number",
      required: true,
      suffix: "Watt",
    },
    {
      id: "water_source",
      label: "Sumber Air",
      type: "multiselect",
      required: false,
      options: [
        "PDAM",
        "Sumur",
        "Sumur Bor",
        "Air Pegunungan",
      ],
    },
    {
      id: "roof_material",
      label: "Material Atap",
      type: "select",
      required: false,
      options: [
        "Genteng Keramik",
        "Genteng Beton",
        "Genteng Metal",
        "Spandek",
        "Dak Beton",
        "Lainnya",
      ],
    },
    {
      id: "wall_material",
      label: "Material Dinding",
      type: "select",
      required: false,
      options: [
        "Bata Merah",
        "Batako",
        "Hebel",
        "Beton",
        "Kayu",
        "Lainnya",
      ],
    },
    {
      id: "floor_material",
      label: "Material Lantai",
      type: "multiselect",
      required: false,
      options: [
        "Keramik",
        "Granit",
        "Marmer",
        "Vinyl",
        "Parket",
        "Teraso",
        "Semen Ekspos",
      ],
    },
    {
      id: "ceiling_material",
      label: "Material Plafon",
      type: "select",
      required: false,
      options: [
        "Gypsum",
        "PVC",
        "Triplek",
        "GRC",
        "Kayu",
      ],
    },
    {
      id: "ceiling_height",
      label: "Tinggi Plafon",
      type: "number",
      required: false,
      suffix: "m",
    },
  ],
};

export default spesifikasiBangunan;
